"""
Vercel Python Serverless Function — /api/predict

Runtime dependencies (requirements.txt):
    onnxruntime==1.20.1
    numpy==1.26.4

Model files required in public/models/ (generated by scripts/export_model.py):
    booster.onnx
    preprocessor_params.json
"""

import json
import math
import os
from http.server import BaseHTTPRequestHandler

import numpy as np
import onnxruntime as rt

# ── Load once per Lambda container ────────────────────────────────────────────
# Vercel docs: "the working directory is the base of your project" for Python
# functions, so relative paths resolve from the project root.
_MODEL_DIR = os.path.join("public", "models")

with open(os.path.join(_MODEL_DIR, "preprocessor_params.json"), encoding="utf-8") as _f:
    _PARAMS = json.load(_f)

_SESSION = rt.InferenceSession(os.path.join(_MODEL_DIR, "booster.onnx"))
_INPUT_NAME = _SESSION.get_inputs()[0].name


def _derive_features(body: dict) -> dict:
    """Compute the 6 derived columns from raw form inputs."""
    annual_premium = float(body["Annual_premium"])
    customer_type = body["Customer_type"]
    customer_region = body["Customer_region"]
    broker_region = body["Broker_region"]
    customer_province = body["Customer_province"]
    broker_province = body["Broker_province"]
    broker_cor = float(body["Broker_cor"])
    payment_frequency = body["Payment_frequency"]

    return {
        **body,
        "Premium_log": math.log1p(annual_premium),
        "Is_enterprise": 1.0 if customer_type == "Enterprise" else 0.0,
        "Customer_Broker_same_region": 1.0 if customer_region == broker_region else 0.0,
        "Customer_Broker_same_province": (
            1.0 if customer_province == broker_province else 0.0
        ),
        "Broker_profitable": 1.0 if broker_cor < 100 else 0.0,
        "Is_monthly_payment": (
            1.0 if payment_frequency.lower() == "monthly" else 0.0
        ),
    }


def _preprocess(data: dict) -> np.ndarray:
    """Reproduce the fitted sklearn ColumnTransformer output."""
    # 1. One-hot encode categorical columns (in the order the transformer saw them)
    cat_features: list[float] = []
    for col in _PARAMS["cat_columns"]:
        cats = _PARAMS["categories"][col]
        val = str(data.get(col, ""))
        cat_features.extend(1.0 if str(c) == val else 0.0 for c in cats)

    # 2. Standard-scale numeric columns
    num_features: list[float] = []
    for i, col in enumerate(_PARAMS["num_columns"]):
        val = float(data.get(col, 0.0))
        mean = _PARAMS["scaler_mean"][i]
        std = _PARAMS["scaler_std"][i] or 1.0
        num_features.append((val - mean) / std)

    return np.array([cat_features + num_features], dtype=np.float32)


class handler(BaseHTTPRequestHandler):  # noqa: N801 – Vercel requires lowercase
    def do_OPTIONS(self) -> None:
        self.send_response(204)
        self._cors_headers()
        self.end_headers()

    def do_POST(self) -> None:
        try:
            length = int(self.headers.get("Content-Length", 0))
            body = json.loads(self.rfile.read(length))

            enriched = _derive_features(body)
            x = _preprocess(enriched)

            outputs = _SESSION.run(None, {_INPUT_NAME: x})
            # XGBoost ONNX outputs: [label, probabilities]
            label_out = outputs[0]
            prob_out = outputs[1]

            prediction = int(label_out[0])
            probability = float(prob_out[0][1])

            self._json_response(
                200,
                {
                    "prediction": prediction,
                    "probability": round(probability, 4),
                    "is_direct_debit": bool(prediction),
                },
            )
        except Exception as exc:  # noqa: BLE001
            self._json_response(500, {"error": str(exc)})

    def _json_response(self, status: int, payload: dict) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self._cors_headers()
        self.end_headers()
        self.wfile.write(body)

    def _cors_headers(self) -> None:
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")

    def log_message(self, *_: object) -> None:
        pass  # suppress default request logging
